apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  db_host: bWlzZXJ2ZXIuY29t
  db_user: dXNlcnh5eg==
  db_pass: Y3Vyc29zZGV2MTIz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: db_host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: db_pass
