apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-stg
  labels:
    env: stg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-dev
  namespace: ns-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-dev
  template:
    metadata:
      labels:
        app: backend-dev
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-stg
  namespace: ns-stg
spec:
  replicas: 6
  selector:
    matchLabels:
      app: backend-stg
  template:
    metadata:
      labels:
        app: backend-stg
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
