apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8081
      nodePort: 30100
  type: NodePort
